
server:
  port: 80

# view resolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    hikari:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/syp
      #username: syp
      #password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://adam.cpiq8808qo9q.ap-northeast-2.rds.amazonaws.com:3306/aircamp
      username: admin
      password: choongang


  profiles:
    include: oauth

# Naver 로그인 아이디 비번

# 카카오 로그인 아이디 비번
  # Security OAuth
  security:
    oauth2.client:
      registration:
        naver:
          clientId: gWHz98Kmv8VTU8BIGrB2
          clientSecret: obsy5k5ACJ
          clientAuthenticationMethod: get
          authorizationGrantType: authorization_code
          redirectUri: http://localhost/oauth/naver/callback
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Naver
        kakao:
          clientId: 18356fc026d73f2a2835407e685fb611
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: http://localhost/oauth/kakao/callback
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me

