# kakao login 
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 18356fc026d73f2a2835407e685fb611
            client-secret: VEcghKPcvFY7dWOUG9TXnqHPfNpoRUoi
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 49497203870-89s3ldd14h0fsgb8024arslgbbrgnc6k.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
 